### ISSUE TITLE
add https to adaminasuit.com

### ISSUE THREAD

**Issue by adamyala** [adaminasuit/adaminasuitdotcom#1]
I think adding https would be a fantastic addition to the site. It would add the assurance that my connection is secure.

It looks like there are some free options https://gist.github.com/cvan/8630f847f579f90e0c014dc5199c337b

In the case of a paid service, what are the thoughts of issuing and ICOing with AdamSuitCoin to raise funds?

**Comment by wesclemens** [comment]
Github pages now supports HTTPS via letsencrypt.org. 

I have updated the DNS once it propagated HTTPS should be available. At that time I will force traffic to HTTPS.

**Comment by wesclemens** [comment]
Fixed
